### ISSUE TITLE
demo_rtt移植到STM32F429IGT6，FS的MSC设备读取成功，但是写入总是cwb/csb出错。

### ISSUE THREAD

**Issue by shanqs123** [xtoolbox/TeenyUSB#1]

**Comment by xtoolbox** [comment]
关于这个问题在STM32F723的开发板也有发现。目前观察到的现象是，开启HS模块的DMA后出现这样的问题，而关闭DMA后没有这个问题。猜测原因是Bulk传输的Nak处理有问题。没有开启DMA时，一次只传输一个包，如果收到NAK后重传当前包。而开启DMA后，NAK处理由DMA控制器来完成，这部分代码还有问题，而关于USB专用DMA控制器的文档资料很少，因此一直没有找到原因。
在FS模块上没有这个问题，不知道你发现的问题是否是这样的。

**Comment by shanqs123** [comment]
您好，我使用的是STM32F4  USB_FS内置PHY，操作从U盘读(SCSI READ 10)比较稳定。  但是操作如"echo 123 a.txt"或者copy文件到usb时，出现错误，debug打印基本如下

`msh /udisc0>echo 123 1                                                                                                              
[D/DFS] open file:/udisc0/1                                                                                                         
[D/DFS] open in filesystem:elm                                                                                                      
[D/DFS] Actual file path: /1                                                                                                        
[D/DFS] open successful                                                                                                             
rt_usbh_storage_read10                                                                                                              
rt_usbh_storage_write10                                                                                                             
csw size error (return -8)                                                                                                                      
usb mass_storage write 1 sector failed  `


wirte10返回的是值是-8 (USB STALL)  不知道我是不是配置了teenyusb的什么宏定义选项导致的
随后pipe上的操作就都不可用了

**Comment by shanqs123** [comment]
测试读取兼容性很棒~偶现某些U盘无法写入~工程上问题已解决

**Comment by xtoolbox** [comment]
> 测试读取兼容性很棒~偶现某些U盘无法写入~工程上问题已解决

感谢您的使用与反馈

**Comment by xtoolbox** [comment]
> 您好，我使用的是STM32F4 USB_FS内置PHY，操作从U盘读(SCSI READ 10)比较稳定。 但是操作如"echo 123 a.txt"或者copy文件到usb时，出现错误，debug打印基本如下
> 
> `msh /udisc0>echo 123 1`
> `[D/DFS] open file:/udisc0/1`
> `[D/DFS] open in filesystem:elm`
> `[D/DFS] Actual file path: /1`
> `[D/DFS] open successful`
> `rt_usbh_storage_read10`
> `rt_usbh_storage_write10`
> `csw size error`
> `usb mass_storage write 1 sector failed `
> 
> wirte10返回的是值是-8 (USB STALL) 不知道我是不是配置了teenyusb的什么宏定义选项导致的
> 随后pipe上的操作就都不可用了

最近修复了一个主机out端点上的问题，增加了bulk传输out NAK后重试的功能，之前你遇到的问题可能是这个原因导致的。最新的主机例程已经可以比较稳定的操作U盘了。

**Comment by shanqs123** [comment]
肥肠感谢，teenyusb对rtt的支持真的是雪中送炭般存在，我稍后再去测试一下看看~
