### ISSUE TITLE
虚拟串口参数改变问题，目前无法更改转到实际的串口发出

### ISSUE THREAD

**Issue by Kevincoooool** [xtoolbox/TeenyUSB#11]
现在看到这一段：

`void cdc_line_coding_change(tusb_cdc_device_t *cdc)
{
  // TODO, handle the line coding change
  //cdc->line_coding.bitrate;
  //cdc->line_coding.databits;
  //cdc->line_coding.stopbits;
  //cdc->line_coding.parity;
}`
这一段是用来改串口的波特率的吗，现在发现这个函数好像没用，我想更改波特率的时候，STM32端能够收到并且重新初始化串口用来做USB转串口

**Comment by xtoolbox** [comment]
cdc_line_coding_change这个函数就是用来配置硬件串口参数的，新的参数会存放在cdc->line_coding这个结构中
