### ISSUE TITLE
composite/bulk demo does not connect

### ISSUE THREAD

**Issue by koendv** [xtoolbox/TeenyUSB#21]
Hi. 
Thank you for writing TeenyUSB. I'm interested in using TeenyUSB on STM32F103 (and GD32F303, same usb hardware as STM32). I have compiled TeenyUSB and tried the STM32F103 composite and the bulk demo. Unfortunately, when I connect the STM32F103 to a linux system, there is no connection. I add the logging output. What should I do?

regards,

koen

f103bulk:

```
[ 2317.374473] usb 1-1.3: new full-speed USB device number 27 using xhci_hcd
[ 2317.476365] usb 1-1.3: not running at top speed; connect to a high speed hub
[ 2317.484076] usb 1-1.3: New USB device found, idVendor=0483, idProduct=0001, bcdDevice= 1.00
[ 2317.484093] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2317.484104] usb 1-1.3: Product: TeenyUSB Custom Bulk
[ 2317.484115] usb 1-1.3: Manufacturer: TeenyUSB
[ 2317.484125] usb 1-1.3: SerialNumber: TUSB123456
[ 2322.671064] usb 1-1.3: can't set config #1, error -110
```
logfile:
[usbmon_bulk.txt](https://github.com/xtoolbox/TeenyUSB/files/7013895/usbmon_bulk.txt)

f103comp:

```
[ 3340.243722] usb 1-1.3: new full-speed USB device number 30 using xhci_hcd
[ 3340.345680] usb 1-1.3: not running at top speed; connect to a high speed hub
[ 3340.352183] usb 1-1.3: New USB device found, idVendor=0483, idProduct=0011, bcdDevice= 1.00
[ 3340.352201] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3340.352216] usb 1-1.3: Product: TeenyUSB Composite DEMO
[ 3340.352230] usb 1-1.3: Manufacturer: TeenyUSB
[ 3340.352243] usb 1-1.3: SerialNumber: TUSB123456
[ 3345.396632] usb 1-1.3: can't set config #1, error -110
```
[usbmon_comp.txt](https://github.com/xtoolbox/TeenyUSB/files/7013915/usbmon_comp.txt)

The logfile also contains a bit of traffic from keyboard and mouse (connected to same usb bus).

linux used:
```
 $ uname -a
Linux raspberrypi 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux

```

**Comment by xtoolbox** [comment]
it seems the set configuration request fail. Can you open the log in the device site to figure out how the set configuration request fails.

**Comment by koendv** [comment]
On Sun, 07 Nov 2021 01:24:56 -0700
XToolBox ***@***.***> wrote:

> it seems the set configuration request fail. Can you open the log in
> the device site to figure out how the set configuration request fails.
> 

Good work. It's always nice to feel appreciated.

koen
